# Generates Vault + RPC SQL and Edge secret hints for OTP email (run from repo root).
# Usage: pwsh -File scripts/generate_otp_mail_setup.ps1

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $root

$envFile = Join-Path $root ".env"
if (-not (Test-Path $envFile)) {
  Write-Error ".env not found. Copy .env.example to .env first."
}

$supabaseUrl = $null
Get-Content $envFile | ForEach-Object {
  if ($_ -match '^\s*SUPABASE_URL\s*=\s*(.+)\s*$') {
    $supabaseUrl = $Matches[1].Trim().Trim('"')
  }
}
if ([string]::IsNullOrWhiteSpace($supabaseUrl)) {
  Write-Error "SUPABASE_URL not found in .env"
}

$edgeUrl = $supabaseUrl.TrimEnd("/") + "/functions/v1/send-password-reset-otp"
# 64 hex chars (32 random bytes)
$internalSecret = ((1..32 | ForEach-Object { '{0:x2}' -f (Get-Random -Maximum 256) }) -join '')

$outDir = Join-Path $root "scripts\_generated"
New-Item -ItemType Directory -Force -Path $outDir | Out-Null

$sqlPath = Join-Path $outDir "otp_mail_setup.sql"
$hintsPath = Join-Path $outDir "edge_function_secrets.txt"

$sql = @"
-- Generated by scripts/generate_otp_mail_setup.ps1 - run once in Supabase SQL Editor.
-- Edge Function URL (must contain /functions/v1/, not /auth/v1/).

create extension if not exists pg_net;

-- If you already created these Vault entries, remove them in Dashboard - Project Settings - Vault
-- or delete from the vault secrets UI, then re-run the two create_secret lines below.

select vault.create_secret(
  '$edgeUrl',
  'otp_mail_edge_url',
  'URL for send-password-reset-otp Edge Function'
);

select vault.create_secret(
  '$internalSecret',
  'otp_mail_internal_secret',
  'Must match Edge Function env INTERNAL_OTP_MAIL_SECRET'
);

create or replace function public.request_password_reset_otp(p_email text)
returns jsonb
language plpgsql
security definer
set search_path = public
as `$`$
declare
  v_otp text;
  v_edge_url text;
  v_internal_secret text;
begin
  if p_email is null or btrim(p_email) = '' then
    raise exception 'Email is required.';
  end if;

  if not exists (select 1 from auth.users where email = lower(btrim(p_email))) then
    raise exception 'No account found for this email.';
  end if;

  v_otp := lpad((floor(random() * 1000000))::int::text, 6, '0');

  update public.password_resets
    set used = true
    where email = lower(btrim(p_email)) and used = false;

  insert into public.password_resets (email, otp_hash, expires_at, used)
  values (
    lower(btrim(p_email)),
    crypt(v_otp, gen_salt('bf')),
    now() + interval '10 minutes',
    false
  );

  begin
    select ds.decrypted_secret into v_edge_url
    from vault.decrypted_secrets ds
    where ds.name = 'otp_mail_edge_url'
    limit 1;

    select ds.decrypted_secret into v_internal_secret
    from vault.decrypted_secrets ds
    where ds.name = 'otp_mail_internal_secret'
    limit 1;

    if v_edge_url is null
       or length(btrim(v_edge_url)) = 0
       or v_internal_secret is null
       or length(btrim(v_internal_secret)) = 0 then
      raise exception 'OTP email delivery is not configured. Add Vault secrets otp_mail_edge_url + otp_mail_internal_secret and deploy send-password-reset-otp.';
    end if;

    if position('/auth/v1/' in lower(btrim(v_edge_url))) > 0 then
      raise exception
        'otp_mail_edge_url must be your Edge Function (.../functions/v1/send-password-reset-otp), not an Auth API URL.';
    end if;
    if position('/functions/v1/' in lower(btrim(v_edge_url))) = 0 then
      raise exception
        'otp_mail_edge_url must include /functions/v1/ (deploy send-password-reset-otp first).';
    end if;

    perform net.http_post(
      url := btrim(v_edge_url),
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'x-internal-secret', btrim(v_internal_secret)
      ),
      body := jsonb_build_object(
        'email', lower(btrim(p_email)),
        'otp', v_otp
      )
    );

    return jsonb_build_object('success', true, 'message', 'OTP sent.');
  exception
    when undefined_table then
      raise exception 'OTP email delivery is not configured: install pg_net and deploy send-password-reset-otp.';
    when undefined_function then
      raise exception 'OTP email delivery is not configured: install pg_net and deploy send-password-reset-otp.';
  end;
